use serde::Serialize;

/// Server to Client message opcodes
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize)]
#[repr(u32)]
pub enum S2CMessageType {
    ItemServerSaysRemove = 0x0024,
    CharacterServerSaysAttemptFailed = 0x00A0,
    ItemUpdateStackSize = 0x0197,
    CombatHandlePlayerDeathEvent = 0x019E,
    QualitiesPrivateRemoveIntEvent = 0x01D1,
    QualitiesRemoveIntEvent = 0x01D2,
    QualitiesPrivateRemoveBoolEvent = 0x01D3,
    QualitiesRemoveBoolEvent = 0x01D4,
    QualitiesPrivateRemoveFloatEvent = 0x01D5,
    QualitiesRemoveFloatEvent = 0x01D6,
    QualitiesPrivateRemoveStringEvent = 0x01D7,
    QualitiesRemoveStringEvent = 0x01D8,
    QualitiesPrivateRemoveDataIdEvent = 0x01D9,
    QualitiesRemoveDataIdEvent = 0x01DA,
    QualitiesPrivateRemoveInstanceIdEvent = 0x01DB,
    QualitiesRemoveInstanceIdEvent = 0x01DC,
    QualitiesPrivateRemovePositionEvent = 0x01DD,
    QualitiesRemovePositionEvent = 0x01DE,
    CommunicationHearEmote = 0x01E0,
    CommunicationHearSoulEmote = 0x01E2,
    QualitiesPrivateRemoveInt64Event = 0x02B8,
    QualitiesRemoveInt64Event = 0x02B9,
    CommunicationHearSpeech = 0x02BB,
    CommunicationHearRangedSpeech = 0x02BC,
    QualitiesPrivateUpdateInt = 0x02CD,
    QualitiesUpdateInt = 0x02CE,
    QualitiesPrivateUpdateInt64 = 0x02CF,
    QualitiesUpdateInt64 = 0x02D0,
    QualitiesPrivateUpdateBool = 0x02D1,
    QualitiesUpdateBool = 0x02D2,
    QualitiesPrivateUpdateFloat = 0x02D3,
    QualitiesUpdateFloat = 0x02D4,
    QualitiesPrivateUpdateString = 0x02D5,
    QualitiesUpdateString = 0x02D6,
    QualitiesPrivateUpdateDataId = 0x02D7,
    QualitiesUpdateDataId = 0x02D8,
    QualitiesPrivateUpdateInstanceId = 0x02D9,
    QualitiesUpdateInstanceId = 0x02DA,
    QualitiesPrivateUpdatePosition = 0x02DB,
    QualitiesUpdatePosition = 0x02DC,
    QualitiesPrivateUpdateSkill = 0x02DD,
    QualitiesUpdateSkill = 0x02DE,
    QualitiesPrivateUpdateSkillLevel = 0x02DF,
    QualitiesUpdateSkillLevel = 0x02E0,
    QualitiesPrivateUpdateSkillAC = 0x02E1,
    QualitiesUpdateSkillAC = 0x02E2,
    QualitiesPrivateUpdateAttribute = 0x02E3,
    QualitiesUpdateAttribute = 0x02E4,
    QualitiesPrivateUpdateAttributeLevel = 0x02E5,
    QualitiesUpdateAttributeLevel = 0x02E6,
    QualitiesPrivateUpdateAttribute2nd = 0x02E7,
    QualitiesUpdateAttribute2nd = 0x02E8,
    QualitiesPrivateUpdateAttribute2ndLevel = 0x02E9,
    QualitiesUpdateAttribute2ndLevel = 0x02EA,
    AdminEnvirons = 0xEA60,
    MovementPositionAndMovementEvent = 0xF619,
    ItemObjDescEvent = 0xF625,
    CharacterSetPlayerVisualDesc = 0xF630,
    CharacterCharGenVerificationResponse = 0xF643,
    LoginAwaitingSubscriptionExpiration = 0xF651,
    LoginLogOffCharacter = 0xF653,
    CharacterCharacterDelete = 0xF655,
    LoginLoginCharacterSet = 0xF658,
    CharacterCharacterError = 0xF659,
    ItemCreateObject = 0xF745,
    LoginCreatePlayer = 0xF746,
    ItemDeleteObject = 0xF747,
    MovementPositionEvent = 0xF748,
    ItemParentEvent = 0xF749,
    InventoryPickupEvent = 0xF74A,
    ItemSetState = 0xF74B,
    MovementSetObjectMovement = 0xF74C,
    MovementVectorUpdate = 0xF74E,
    EffectsSoundEvent = 0xF750,
    EffectsPlayerTeleport = 0xF751,
    EffectsPlayScriptId = 0xF754,
    EffectsPlayScriptType = 0xF755,
    LoginAccountBanned = 0xF7C1,
    AdminReceiveAccountData = 0xF7CA,
    AdminReceivePlayerData = 0xF7CB,
    ItemUpdateObject = 0xF7DB,
    LoginAccountBooted = 0xF7DC,
    CommunicationTurbineChat = 0xF7DE,
    LoginEnterGameServerReady = 0xF7DF,
    CommunicationTextboxString = 0xF7E0,
    LoginWorldInfo = 0xF7E1,
    DDDDataMessage = 0xF7E2,
    DDDErrorMessage = 0xF7E4,
    DDDInterrogationMessage = 0xF7E5,
    DDDBeginDDDMessage = 0xF7E7,
    DDDOnEndDDD = 0xF7EA,
    OrderedGameEvent = 0xF7B0,
    Unknown = 0xFFFFFFFF,
}

impl S2CMessageType {
    pub fn from_u32(value: u32) -> Self {
        match value {
            0x0024 => S2CMessageType::ItemServerSaysRemove,
            0x00A0 => S2CMessageType::CharacterServerSaysAttemptFailed,
            0x0197 => S2CMessageType::ItemUpdateStackSize,
            0x019E => S2CMessageType::CombatHandlePlayerDeathEvent,
            0x01D1 => S2CMessageType::QualitiesPrivateRemoveIntEvent,
            0x01D2 => S2CMessageType::QualitiesRemoveIntEvent,
            0x01D3 => S2CMessageType::QualitiesPrivateRemoveBoolEvent,
            0x01D4 => S2CMessageType::QualitiesRemoveBoolEvent,
            0x01D5 => S2CMessageType::QualitiesPrivateRemoveFloatEvent,
            0x01D6 => S2CMessageType::QualitiesRemoveFloatEvent,
            0x01D7 => S2CMessageType::QualitiesPrivateRemoveStringEvent,
            0x01D8 => S2CMessageType::QualitiesRemoveStringEvent,
            0x01D9 => S2CMessageType::QualitiesPrivateRemoveDataIdEvent,
            0x01DA => S2CMessageType::QualitiesRemoveDataIdEvent,
            0x01DB => S2CMessageType::QualitiesPrivateRemoveInstanceIdEvent,
            0x01DC => S2CMessageType::QualitiesRemoveInstanceIdEvent,
            0x01DD => S2CMessageType::QualitiesPrivateRemovePositionEvent,
            0x01DE => S2CMessageType::QualitiesRemovePositionEvent,
            0x01E0 => S2CMessageType::CommunicationHearEmote,
            0x01E2 => S2CMessageType::CommunicationHearSoulEmote,
            0x02B8 => S2CMessageType::QualitiesPrivateRemoveInt64Event,
            0x02B9 => S2CMessageType::QualitiesRemoveInt64Event,
            0x02BB => S2CMessageType::CommunicationHearSpeech,
            0x02BC => S2CMessageType::CommunicationHearRangedSpeech,
            0x02CD => S2CMessageType::QualitiesPrivateUpdateInt,
            0x02CE => S2CMessageType::QualitiesUpdateInt,
            0x02CF => S2CMessageType::QualitiesPrivateUpdateInt64,
            0x02D0 => S2CMessageType::QualitiesUpdateInt64,
            0x02D1 => S2CMessageType::QualitiesPrivateUpdateBool,
            0x02D2 => S2CMessageType::QualitiesUpdateBool,
            0x02D3 => S2CMessageType::QualitiesPrivateUpdateFloat,
            0x02D4 => S2CMessageType::QualitiesUpdateFloat,
            0x02D5 => S2CMessageType::QualitiesPrivateUpdateString,
            0x02D6 => S2CMessageType::QualitiesUpdateString,
            0x02D7 => S2CMessageType::QualitiesPrivateUpdateDataId,
            0x02D8 => S2CMessageType::QualitiesUpdateDataId,
            0x02D9 => S2CMessageType::QualitiesPrivateUpdateInstanceId,
            0x02DA => S2CMessageType::QualitiesUpdateInstanceId,
            0x02DB => S2CMessageType::QualitiesPrivateUpdatePosition,
            0x02DC => S2CMessageType::QualitiesUpdatePosition,
            0x02DD => S2CMessageType::QualitiesPrivateUpdateSkill,
            0x02DE => S2CMessageType::QualitiesUpdateSkill,
            0x02DF => S2CMessageType::QualitiesPrivateUpdateSkillLevel,
            0x02E0 => S2CMessageType::QualitiesUpdateSkillLevel,
            0x02E1 => S2CMessageType::QualitiesPrivateUpdateSkillAC,
            0x02E2 => S2CMessageType::QualitiesUpdateSkillAC,
            0x02E3 => S2CMessageType::QualitiesPrivateUpdateAttribute,
            0x02E4 => S2CMessageType::QualitiesUpdateAttribute,
            0x02E5 => S2CMessageType::QualitiesPrivateUpdateAttributeLevel,
            0x02E6 => S2CMessageType::QualitiesUpdateAttributeLevel,
            0x02E7 => S2CMessageType::QualitiesPrivateUpdateAttribute2nd,
            0x02E8 => S2CMessageType::QualitiesUpdateAttribute2nd,
            0x02E9 => S2CMessageType::QualitiesPrivateUpdateAttribute2ndLevel,
            0x02EA => S2CMessageType::QualitiesUpdateAttribute2ndLevel,
            0xEA60 => S2CMessageType::AdminEnvirons,
            0xF619 => S2CMessageType::MovementPositionAndMovementEvent,
            0xF625 => S2CMessageType::ItemObjDescEvent,
            0xF630 => S2CMessageType::CharacterSetPlayerVisualDesc,
            0xF643 => S2CMessageType::CharacterCharGenVerificationResponse,
            0xF651 => S2CMessageType::LoginAwaitingSubscriptionExpiration,
            0xF653 => S2CMessageType::LoginLogOffCharacter,
            0xF655 => S2CMessageType::CharacterCharacterDelete,
            0xF658 => S2CMessageType::LoginLoginCharacterSet,
            0xF659 => S2CMessageType::CharacterCharacterError,
            0xF745 => S2CMessageType::ItemCreateObject,
            0xF746 => S2CMessageType::LoginCreatePlayer,
            0xF747 => S2CMessageType::ItemDeleteObject,
            0xF748 => S2CMessageType::MovementPositionEvent,
            0xF749 => S2CMessageType::ItemParentEvent,
            0xF74A => S2CMessageType::InventoryPickupEvent,
            0xF74B => S2CMessageType::ItemSetState,
            0xF74C => S2CMessageType::MovementSetObjectMovement,
            0xF74E => S2CMessageType::MovementVectorUpdate,
            0xF750 => S2CMessageType::EffectsSoundEvent,
            0xF751 => S2CMessageType::EffectsPlayerTeleport,
            0xF754 => S2CMessageType::EffectsPlayScriptId,
            0xF755 => S2CMessageType::EffectsPlayScriptType,
            0xF7B0 => S2CMessageType::OrderedGameEvent,
            0xF7C1 => S2CMessageType::LoginAccountBanned,
            0xF7CA => S2CMessageType::AdminReceiveAccountData,
            0xF7CB => S2CMessageType::AdminReceivePlayerData,
            0xF7DB => S2CMessageType::ItemUpdateObject,
            0xF7DC => S2CMessageType::LoginAccountBooted,
            0xF7DE => S2CMessageType::CommunicationTurbineChat,
            0xF7DF => S2CMessageType::LoginEnterGameServerReady,
            0xF7E0 => S2CMessageType::CommunicationTextboxString,
            0xF7E1 => S2CMessageType::LoginWorldInfo,
            0xF7E2 => S2CMessageType::DDDDataMessage,
            0xF7E4 => S2CMessageType::DDDErrorMessage,
            0xF7E5 => S2CMessageType::DDDInterrogationMessage,
            0xF7E7 => S2CMessageType::DDDBeginDDDMessage,
            0xF7EA => S2CMessageType::DDDOnEndDDD,
            _ => S2CMessageType::Unknown,
        }
    }
}

/// Client to Server message opcodes
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize)]
#[repr(u32)]
pub enum C2SMessageType {
    LoginSendEnterWorld = 0xF657,
    OrderedGameAction = 0xF7B1,
    Unknown = 0xFFFFFFFF,
}

impl C2SMessageType {
    pub fn from_u32(value: u32) -> Self {
        match value {
            0xF657 => C2SMessageType::LoginSendEnterWorld,
            0xF7B1 => C2SMessageType::OrderedGameAction,
            _ => C2SMessageType::Unknown,
        }
    }
}

/// Message direction
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize)]
#[allow(dead_code)]
pub enum MessageDirection {
    ServerToClient,
    ClientToServer,
}
